### ISSUE TITLE
Wysiwyg & image upload

### ISSUE THREAD

**Issue by Fausto95** [Radrw/strapi-pro#1]
Hey, 
I've cloned your repo and create a new strapi project in dev mode then I ran 'npm run setup' in your repo's folder that I cloned to create a symlink with my project.
But there's no wysiwyg and image upload option in the content-type-builder when I go to localhost /admin

**Comment by patrickmuhi** [comment]
@Fausto95 Your api's model should include the type_render and type_mongo, something like this
<img width="383" alt="screen shot 2018-02-15 at 3 51 48 pm" src="https://user-images.githubusercontent.com/14908307/36259850-3257841a-1268-11e8-9d3c-0bd62b12debc.png">


Then create a new item from your content type, you will see the custom components.

**Comment by Fausto95** [comment]
<img width="1440" alt="capture d ecran 2018-02-15 a 16 02 31" src="https://user-images.githubusercontent.com/23306911/36263134-b7ee8230-1269-11e8-8e6f-6d24c2600ff5.png">

Just did that and then when go to create a new item from my content type, it's sends me a blank page in this url: http://localhost:1337/admin/plugins/content-manager/product/create?source=content-manager

**Comment by patrickmuhi** [comment]
You have to run strapi in development mode, 

`cd admin`
`npm start`

then open your browser on port 4000,

PS: remember to keep the 1337 running as well
